/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: 77da4230-7a48-4ac9-8bd7-caa88b8685c6
*/
package util.sideeffects;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.stream.Stream;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

@SuppressWarnings("unused")
public class SideEffectTest {
	
//region Scenarios
	//A new scenario
	@ParameterizedTest(name = "{1} [{index}] {2}")
	@MethodSource({"Scenario1Source"})
	public void Scenario1Test(Scenario1TestData data, String TestName, String TestDescription) {
		ActualResultStorage.setStorage(); //saves the results of the called Methods
		
		assertion(data, data.S1M1.methodName, data.C1, data.S1M1.expectedResult, data.S1M1.call());
	}
//endregion

//region Data

//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
	//A new scenario
	private static Stream<Arguments> Scenario1Source() {
		return Stream.of(
			Arguments.of(
				new Scenario1TestData(
					/* SideEffect C1 = */ new SideEffect(100),
					/* S1M1 = */ new S1M1Parameters<>(
						/* Integer steps = */ 10,
						/* referencingMethodName = */ "",
						/* expectedResult = */ new Result<>(
							/* assertType = */ AssertType.EXPECTED_VALUE,
							/* sideEffects = */ List.of(
								new SideEffect<>(
									/* expectedValue = */ new SideEffect(110),
									/* actualValueAccessor = */ t -> t.C1
								)
							)
						)
					)
				),
				/* testCaseName = */ "p1",
				/* testCaseDescription = */ ""
			)
		);
	}
//endregion

//region Types

//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
	static class Scenario1TestData {
	    public final SideEffect C1;
	    public final S1M1Parameters<Scenario1TestData> S1M1;
	    
	    public Scenario1TestData(SideEffect C1, S1M1Parameters<Scenario1TestData> S1M1) {
	    	this.C1 = C1;
	    	this.S1M1 = S1M1;
	    }
	}

	static class S1M1Parameters<TestData> {
		public final String methodName = "S1M1";
	    public final ObjectWrapper<Integer> steps;
	    public final Result<TestData, SideEffect, VoidR> expectedResult;
		public S1M1Parameters(Integer steps, String referencingMethodName, Result<TestData, SideEffect, VoidR> expectedResult) {
			this.steps = new ObjectWrapper<>(steps, referencingMethodName);
	   		this.expectedResult = expectedResult;
	    }
	    
	    public ExceptionFunction<SideEffect, VoidR> call() {
	    	return asFunc(i ->
	    	 i.addSteps(steps.get()));
		}
	}
//endregion

//region Utility Classes

//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
	public static class ObjectWrapper<T> {
		public T object;
		public String referencingMethodName;
		
		public ObjectWrapper(T object, String referencingMethodName) {
			this.object = object;
			this.referencingMethodName = referencingMethodName;
		}
		
		public T get() {
			return ActualResultStorage.getOrDefault(referencingMethodName, object);
		}
	}
	
	public static class ActualResultStorage {
		private static Map<String, Object> actualResultMap = new HashMap<>();
		
		public static void setStorage() {
			actualResultMap = new HashMap<>();
		}
		
		public static <T> void put(String key, T value) {
			actualResultMap.put(key, value);
		}
		
		@SuppressWarnings("unchecked")
		public static <T> T getOrDefault(String key, T defaultValue) {
			return (T) actualResultMap.getOrDefault(key, defaultValue);
		}
	}
	
	static class Result<TestData, TInstance, TReturn> {
		public final AssertType assertType;
		public final TReturn expectedReturnValue;
		public final Class<? extends Throwable> expectedException;
		public final BiConsumer<TInstance, TReturn> customAction;
		public final List<SideEffect<TestData>> sideEffects;
		
		public Result(AssertType assertType) {
			this(assertType, (TReturn) null, null);
		}
	
		public Result(AssertType assertType, List<SideEffect<TestData>> sideEffects) {
			this(assertType, (TReturn) null, sideEffects);
		}
	
		public Result(AssertType assertType, TReturn expectedReturnValue) {
			this(assertType, expectedReturnValue, null);
		}
	
		public Result(AssertType assertType, Class<? extends Throwable> expectedException) {
			this(assertType, expectedException, null);
		}
	
		public Result(AssertType assertType, BiConsumer<TInstance, TReturn> customAction) {
			this(assertType, customAction, null);
		}
	
		public Result(AssertType assertType, TReturn expectedReturnValue, List<SideEffect<TestData>> sideEffects) {
			this(assertType, expectedReturnValue, null, null, sideEffects);
		}
	
		public Result(AssertType assertType, Class<? extends Throwable> expectedException, List<SideEffect<TestData>> sideEffects) {
			this(assertType, null, expectedException, null, sideEffects);
		}
	
		public Result(AssertType assertType, BiConsumer<TInstance, TReturn> customAction, List<SideEffect<TestData>> sideEffects) {
			this(assertType, null, null, customAction, sideEffects);
		}
	
		public Result(AssertType assertType, TReturn expectedReturnValue, Class<? extends Throwable> expectedException,
			BiConsumer<TInstance, TReturn> customAction, List<SideEffect<TestData>> sideEffects) {
			this.assertType = assertType;
			this.expectedReturnValue = expectedReturnValue;
			this.expectedException = expectedException;
			this.customAction = customAction;
			this.sideEffects = sideEffects;
		}
	}
	
	static class SideEffect<TestData> {
	    public final Object expectedValue;
	    public final Function<TestData, Object> actualValueAccessor;
	    
		public SideEffect(Object expectedValue, Function<TestData, Object> actualValueAccessor) {
			this.expectedValue = expectedValue;
			this.actualValueAccessor = actualValueAccessor;
		}
	}
	
	public enum AssertType {
	    EXCEPTION, EXPECTED_VALUE, CUSTOM_ASSERTION
	}
	
	static class VoidR {
	}
	
	private static <I> ExceptionFunction<I, VoidR> asFunc(ExceptionConsumer<I> action) {
		return i -> {
			action.accept(i);
			return null;
		};
	}
	
	@FunctionalInterface
	public interface ExceptionFunction<I, R> {
		R apply(I i) throws Exception;
	}
	
	@FunctionalInterface
	public interface ExceptionConsumer<I> {
		void accept(I i) throws Exception;
	}
	
	private <TestData, I, R> void assertion(TestData data, String methodName, I instance, Result<TestData, I, R> expectedResult, ExceptionFunction<I, R> toApply) {
		if (expectedResult == null) {
			ActualResultStorage.put(methodName, assertDoesNotThrow(() -> toApply.apply(instance)));
			return;
		}
		R actualResult = null;
		if (expectedResult.assertType.equals(AssertType.EXCEPTION)) {
			assertThrows(expectedResult.expectedException, () -> toApply.apply(instance));
		} else {
			actualResult = assertDoesNotThrow(() -> toApply.apply(instance));
			if (expectedResult.assertType.equals(AssertType.EXPECTED_VALUE) &&
					!(expectedResult.expectedReturnValue instanceof VoidR)) {
				assertEquals(expectedResult.expectedReturnValue, actualResult);
			} else if (expectedResult.assertType.equals(AssertType.CUSTOM_ASSERTION)) {
				expectedResult.customAction.accept(instance, actualResult);
			}
			if (expectedResult.sideEffects != null) {
				for (var sideEffect : expectedResult.sideEffects) {
					var sideEffectResult = sideEffect.actualValueAccessor.apply(data);
					assertEquals(sideEffect.expectedValue, sideEffectResult);
				}
			}
		}
		ActualResultStorage.put(methodName, actualResult);
	}
//endregion
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAA/+0ZbU/bOPhzkfgPXj+c0ikL6328lh496OmQxkC0Y5NOp8mkLnhLk1zswDjU/36PX+LYicMo28SXIZE
mzuPn/dXJcfwZXxFUcppEjC4JWa1IzNlod2d3h67zrOCIccxpjLLiKvpUppTDNaecFBHOaTRljBScZimLsLw9ygh7m/
HFdZHdjp6IY/ZviRP21N2StCPBJ3yDIyniX5hdn+B85Hn1hjLuW+8AX5VpLKhGf9BDoF2uSfEg2J/6xgfEeEHwOprLH
5vxtsQ5LvCaRWfih8AC/Y8sF8TmvHNPXmQ3YOEimhZXwG7K2TabTgi/zpbzrCxiIlk8mJd5XhDG3uMipekVC/plWjKy
7A92d/LyMgGLxQmYBM0BwUz6leAU3e/u9HZ39vYKcgX6QPOYpLigGYPlvb0pSsktYnoNlg5aogYpPKN91L8fbtDf9zR
dki+bf9D9rxtBuXdgcxrc9yv8Q7XS3wggzd9NRpeGgaFE7jwdYY7REi4hAuOAkEisvgX6zsIRYXFBc2HegRSvN405uP
A5YWXC5zwrIMYiRqrbYDBCe3sM3xCG+DVBhYRjKFvJxxgnCVkiJYdQS0/848rPA8WQuEbz4ckwWktAxZVcPRzar8mXH
FRPloob+40gFAwGYM7eRliEpEtlFGFfYyChBLWw/1x/gvhZQjAjaJ0t6eoO9EQZYkSGFMrS5A7RVCrvJFsS0B4FTaM0
4+iaFKR6F8O7EF2SGIOfogyWilsKd5SjW5okSK1DJF8J2HQFLsLZi2eW3BcUeUFvMCdVYlSJY2zieoIaTh9otywIL4t
Uw0fZKhCLPbPPrPQEvVYk6He9vZdWSKPDIcTiyz3JYr0cDF+/HoTWBvA3Cw6eTFyz8aTCLCCPU06uSAGykZypLcPXoQ
VQkBXYNI0h+k6M5yvAft8GdB2/pq6eLaoCWNeOu1yjmprnaPbhbHa4mB19vJi+eTcL7V3MCKxZFVWkVqNRpQGzqTpMX
uCkJH5NDmtNVszK9CK3TOMYcjA4u9zK0asJ4pAAaviBuTV31Y3+rbADYg6mPoQws1SaD/vt91bGqzQvYSTGryUUoVT2
M6M8m+Q9nTZ0dW4VPJEqEPzpIrmiKU7ciB95IdygbuGdSIhqq4uhnWsceuEjkQ8M7z1hzkjmpppdtahTkc3MRjlsSzU
u0ZqWTKau8KobWNsJqS/29726Or38BJK9L3Cek2KsU95E5TzvBp2zKhZCyx4huoA25nzSyHcji0dXkMBJsaaT8ebV8A
mUdbFR2q7SuEhqrtSTQNP3Eh5oNWg0rVzeFrYyZNu7Zl9iInNV1YSPPTKoZqh2IF0rMRObAgqJtXqDaISXy7lgXokQX
REOfZRkubd5OPm9g4af8jt0KDzsZxp8Rsmr4HBC3nXRhRvqC5TJ105oPRA8o6p317AO8qDC9nAAOsGkNoD3W3yoN11N
UTdfmwZzCyS9WJPT3u+bYwDstDgiKwxrQUfSUPw5AdHr0LiHhFa62+TCHD5Wigq1Iie6D1J74b1OM3rIhwQzaFpA45J
znz2Paakfh6+pOY1UeItEnJcwRiqTfiZ3IWj2RnRqHUQiAS7hFJRLwjtlx9ck/qwGbR8T0pK1iVxWlmr1wuZIGztYDJ
oadY0tUTgImgZ2LNuqHIvjFADSGBxkcS5p+kpp3XlbTfmoBaYxWIVAPEq22sAy245/B2AOaZkheUaELxNS1y5TJNq76
yOesU+EuGQ8W09j/2YxEVj1pu4iJvb00HRUpbvAqws7JQT1cggGVCwNUFomSSivtYkeiT18JMeP5sLesz0zD5i5kwMP
7JOVsY3nfJUhA/lkdrZwxU5ubKAnM/KAXb7ZgzrtF34Xl9rGpN8si2K4wwG+VZItvOE7CaKuLuIfFuBbmkry/YNVEmH
7nKhRn5qjihHEmVfcMuXuMcJYO9zCpOBtMQC0VYH07OWcTjWrTVfZ9unDfyag2jD3CMs7vZq5q+4F3BbOOcqyjghMl1
0fh/mIhltScCzaPIFriVNZ3nvo1sG/p+slabm2m5tKpbMPh7OzxfHp2xA1ThrR4bv54vTk43Q+n50LiA6LyQlW4qsou
q3z+HjimYGPzeirZ1wDYiLoWGqvriW6URTDcN3Miq9bOBZbA6riv4ITyUIpY1TzdlAxgBNxDlGscExqJdFqyc/wuaZ7
jmCGSu6CY0QHMIGKD37IiZOnErNFl5RkR6/F+xq1Su2WEyqeFRLzAcf/acn+jAOUTO5qtdEKZ/OzTpe+eDYVqtIWpCs
UNM9S9lUPoC3qG/nEiGKz1/7UG8AM9coQi5R1KhmqoxHtF/WEc+7MG2i/9pg2n1bmjYj8QGxVlMgE0cCMWdbH4CYqTz
l+mH/FMiIJI54pzlSCLTSiFLK9mHaCGKBfftlVR/kvukS0q1BFPVupyDe66tnf3R+BKXTspmXR6tlWpGaOq5lqYLGLn
Ek4Jkp8DHWp2K6LL1zv760gqwc3uLDKJfoNdSMwG3vuJuMZ9ZKvgmi/EIlAc90whrW9UfKatKr9m1p4eXlUQDe11zzB
hOf/AZkxxmcsIgAA
END_CODEGEN_DATA
*/
